[package]
name = "VMWare Fusion Wrapper CLI"
version = "0.1.0"
authors = ["Mat Wood <mat@thepacketgeek.com>"]
edition = "2018"


[dependencies]
anyhow = "1"
lazy_static = "1.4.0"
regex = "1.3.5"
structopt = { version = "0.3", default-features = false }
walkdir = "2"